/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itp_library;
import Mapa.Mapa;
import Graph.AdaptablePriorityQueue;
import Graph.AdjacencyMapGraph;
import Graph.Edge;
import Graph.Entry;
import Graph.Graph;
import Graph.HeapAdaptablePriorityQueue;
import Graph.Map;
import Graph.ProbeHashMap;
import Graph.Vertex;
import Mapa.MapGraph;
import static Mapa.Mapa.Piso;
import Mapa.OfficePoint;
import Mapa.RoadLink;
import Mapa.RoadPoint;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicTabbedPaneUI;


/**
 *
 * @author Abel
 */
public class MapaPanel extends javax.swing.JPanel {

    /**
     * Creates new form MapaPanel
     */
                
    ArrayList<Vertex<RoadPoint>> Nodos  = MapGraph.getRoadPoints();
    
    public static ArrayList<Edge<RoadLink>> NodosShortestPath = null; //Lista de aristas que forman parte del camino solicitado
    public static HashMap<String, Vertex> hashMap = new HashMap<>(); //Asocia nombres de Oficinas con el objeto 
    
    String paths[] = {
        "/Imagenes/piso_1.png",
        "/Imagenes/piso_2.png",
        "/Imagenes/piso_3.png"
    };
    int pisoActual = 0;
    
    
    public MapaPanel() {
        initComponents();
                
        iniciarHashmap();
        iniciarCombobox();
        aulaNuevoP.setBackground(new Color(255, 255, 255, 100));
    }

    private void iniciarHashmap(){
        for(Vertex<RoadPoint> rp :MapGraph.getRoadPoints()){
            RoadPoint p = rp.getElement();
            if(p instanceof OfficePoint){
                hashMap.put(((OfficePoint) p).getNombre(), rp);  
            }
        }        
    }
    
    private void iniciarCombobox(){   
        Set<String> keySet = hashMap.keySet(); //Obtener los key del hashmap (Los nombres de oficinas)
        List<String> sortedKeys = new ArrayList<>(keySet); //Pasarlos a un arreglo para ser ordenados
        Collections.sort(sortedKeys); //Ordenarlos
        
        for (String clave : sortedKeys) { //Agregarlos a los JComboBox
            this.Nodo1Box.addItem(clave);                            
            this.Nodo2Box.addItem(clave);  
        }        
    }
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Etiquetas = new javax.swing.JRadioButton();
        Distancias = new javax.swing.JRadioButton();
        app_name1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Nodo1Box = new javax.swing.JComboBox<>();
        Nodo2Box = new javax.swing.JComboBox<>();
        app_name3 = new javax.swing.JLabel();
        NivelLabel = new javax.swing.JLabel();
        fotosPanel = new javax.swing.JTabbedPane();
        jPanelPiso1 = new Mapa(this.paths[0],Piso.PRIMER_PISO);
        aulaNuevoP = new javax.swing.JPanel();
        jPanelPiso2 = new Mapa(this.paths[1],Piso.SEGUNDO_PISO);
        jPanelPiso3 = new Mapa(this.paths[2],Piso.TERCER_PISO);
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Etiquetas.setText("Etiquetas");
        Etiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtiquetasActionPerformed(evt);
            }
        });
        add(Etiquetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, -1));

        Distancias.setText("Recorrido");
        Distancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistanciasActionPerformed(evt);
            }
        });
        add(Distancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, -1, -1));

        app_name1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_name1.setText("Ruta");
        add(app_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, -1, 40));

        jButton1.setText("Mostrar Ruta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 100, 50));

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setText("Fin:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, -1, -1));

        Nodo1Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        Nodo1Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nodo1BoxActionPerformed(evt);
            }
        });
        add(Nodo1Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, 120, -1));

        Nodo2Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        Nodo2Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nodo2BoxActionPerformed(evt);
            }
        });
        add(Nodo2Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 120, -1));

        app_name3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_name3.setText("MAPA");
        add(app_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, 40));

        NivelLabel.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        NivelLabel.setText("NIVEL 1");
        add(NivelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, -1, -1));

        fotosPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanelPiso1.setBackground(new java.awt.Color(255, 255, 255));

        aulaNuevoP.setBackground(new java.awt.Color(255, 255, 255));
        aulaNuevoP.setForeground(new java.awt.Color(51, 51, 51));
        aulaNuevoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aulaNuevoPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aulaNuevoPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout aulaNuevoPLayout = new javax.swing.GroupLayout(aulaNuevoP);
        aulaNuevoP.setLayout(aulaNuevoPLayout);
        aulaNuevoPLayout.setHorizontalGroup(
            aulaNuevoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        aulaNuevoPLayout.setVerticalGroup(
            aulaNuevoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelPiso1Layout = new javax.swing.GroupLayout(jPanelPiso1);
        jPanelPiso1.setLayout(jPanelPiso1Layout);
        jPanelPiso1Layout.setHorizontalGroup(
            jPanelPiso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPiso1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(aulaNuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(712, Short.MAX_VALUE))
        );
        jPanelPiso1Layout.setVerticalGroup(
            jPanelPiso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPiso1Layout.createSequentialGroup()
                .addComponent(aulaNuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 562, Short.MAX_VALUE))
        );

        fotosPanel.addTab("", jPanelPiso1);
        jPanelPiso1.getAccessibleContext().setAccessibleName("");

        jPanelPiso2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelPiso2Layout = new javax.swing.GroupLayout(jPanelPiso2);
        jPanelPiso2.setLayout(jPanelPiso2Layout);
        jPanelPiso2Layout.setHorizontalGroup(
            jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanelPiso2Layout.setVerticalGroup(
            jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        fotosPanel.addTab("", jPanelPiso2);

        jPanelPiso3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelPiso3Layout = new javax.swing.GroupLayout(jPanelPiso3);
        jPanelPiso3.setLayout(jPanelPiso3Layout);
        jPanelPiso3Layout.setHorizontalGroup(
            jPanelPiso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanelPiso3Layout.setVerticalGroup(
            jPanelPiso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        fotosPanel.addTab("", jPanelPiso3);

        add(fotosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 880, 630));

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel8.setText("Inicio:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/down.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 530, 90, 80));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/up.png"))); // NOI18N
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 390, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void DistanciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistanciasActionPerformed
        // TODO add your handling code here:
        if(Distancias.isSelected()){
            ((Mapa)jPanelPiso1).ShowTotalPath(true);
            ((Mapa)jPanelPiso2).ShowTotalPath(true);
            ((Mapa)jPanelPiso3).ShowTotalPath(true);
            this.fotosPanel.getSelectedComponent().repaint();
        }
        else{
            ((Mapa)jPanelPiso1).ShowTotalPath(false);
            ((Mapa)jPanelPiso2).ShowTotalPath(false);
            ((Mapa)jPanelPiso3).ShowTotalPath(false);          
            this.fotosPanel.getSelectedComponent().repaint();
        }         
    }//GEN-LAST:event_DistanciasActionPerformed

    private void EtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtiquetasActionPerformed
        // TODO add your handling code here:
        if(Etiquetas.isSelected()){         
            ((Mapa)jPanelPiso1).setMostrarEnumeracionGrafo(true);
            ((Mapa)jPanelPiso2).setMostrarEnumeracionGrafo(true);
            ((Mapa)jPanelPiso3).setMostrarEnumeracionGrafo(true);
            this.fotosPanel.getSelectedComponent().repaint();
        }
        else{
            ((Mapa)jPanelPiso1).setMostrarEnumeracionGrafo(false);
            ((Mapa)jPanelPiso2).setMostrarEnumeracionGrafo(false);
            ((Mapa)jPanelPiso3).setMostrarEnumeracionGrafo(false);
            this.fotosPanel.getSelectedComponent().repaint();          
        }                
    }//GEN-LAST:event_EtiquetasActionPerformed

    private void Nodo1BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nodo1BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nodo1BoxActionPerformed

    private void Nodo2BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nodo2BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nodo2BoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Vertex a = hashMap.get((String) Nodo1Box.getSelectedItem());
            Vertex b = hashMap.get((String) Nodo2Box.getSelectedItem());
            //((Mapa)jPanelPiso1).VerRuta( true);
            //((Mapa)jPanelPiso1).repaint();
            
            ArrayList<Vertex<RoadPoint>> Nodos  = MapGraph.getRoadPoints();                 
            MapaPanel.NodosShortestPath  = MapGraph.PaintShortestPath(MapGraph.grafo, a, b);                       
            this.fotosPanel.getSelectedComponent().repaint();
            
        }catch(Exception e){
            MapaPanel.NodosShortestPath  = null;
            //((Mapa)jPanelPiso1).VerRuta(false);
            this.fotosPanel.getSelectedComponent().repaint();
            //((Mapa)jPanelPiso1).repaint();
        }     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        pisoActual = (pisoActual-1); if(pisoActual == -1) pisoActual =2;
        this.fotosPanel.setSelectedIndex(pisoActual);
        this.NivelLabel.setText("NIVEL "+(pisoActual+1));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pisoActual = (pisoActual+1)%3;
        this.fotosPanel.setSelectedIndex(pisoActual); //Cambiar al panel con el mapa que contiene el piso actual
        this.NivelLabel.setText("NIVEL "+(pisoActual+1)); //Etiqueta        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void aulaNuevoPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aulaNuevoPMouseEntered
        aulaNuevoP.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_aulaNuevoPMouseEntered

    private void aulaNuevoPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aulaNuevoPMouseExited
        aulaNuevoP.setBackground(new Color(254, 254, 254));
    }//GEN-LAST:event_aulaNuevoPMouseExited


 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Distancias;
    private javax.swing.JRadioButton Etiquetas;
    private javax.swing.JLabel NivelLabel;
    private javax.swing.JComboBox<String> Nodo1Box;
    private javax.swing.JComboBox<String> Nodo2Box;
    private javax.swing.JLabel app_name1;
    private javax.swing.JLabel app_name3;
    private javax.swing.JPanel aulaNuevoP;
    private javax.swing.JTabbedPane fotosPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelPiso1;
    private javax.swing.JPanel jPanelPiso2;
    private javax.swing.JPanel jPanelPiso3;
    // End of variables declaration//GEN-END:variables
}
